### ISSUE TITLE
v2.1.0 is released but Version is still "2.0.5" ?

### ISSUE THREAD

**Issue by ukai** [googleapis/gax-go#130]
https://pkg.go.dev/github.com/googleapis/gax-go/v2
shows `Version: v2.1.0 Latest` 

but
```
const Version = "2.0.5"
```

tag 2.1.0 is unexpected one?

**Comment by vchudnov-g** [comment]
Any updates on this?

**Comment by codyoss** [comment]
https://github.com/googleapis/gax-go/releases/tag/v2.1.1
