### ISSUE TITLE
wrong module version in go.mod file makes "go get ..." of the module fail

### ISSUE THREAD

**Issue by sjakobs** [googleapis/gax-go#217]
In a recent [commit](https://github.com/googleapis/gax-go/commit/735836c34b8124d657958d469998865569e14742) a bot changed the version of a required module such that it does no longer conform to the go.mod [specification](https://go.dev/doc/modules/gomod-ref#require-syntax). This leads to the following error

go: downloading github.com/googleapis/gax-go/v2 v2.5.0
go: github.com/googleapis/gax-go/v2@v2.5.0: parsing go.mod: go.mod:8:2: require google.golang.org/genproto: version "b98a9ff5e252" invalid: must be of the form v1.2.3

#### Environment details

  - Programming language: Go
  - OS: Linux
  - Language runtime version: go1.18.2
  - Package version: googleapis/gax-go/v2

#### Steps to reproduce

  1. go get github.com/googleapis/gax-go/v2

**Comment by codyoss** [comment]
Thanks for the report we have a fix out and will cut a release shortly. Sorry for the inconvenience.

**Comment by shollyman** [comment]
https://github.com/googleapis/gax-go/releases/tag/v2.5.1
