### ISSUE TITLE
add go mod tidy check to CI

### ISSUE THREAD

**Issue by codyoss** [googleapis/gax-go#220]
A recent renovate PR, #214, failed and put an improper version into our go.mod file. We should add a similar check that we have in other repos to detect if there are diffs when running "go mod tidy" over the changes.

**Comment by quartzmo** [comment]
Is [this](https://github.com/googleapis/gax-go/blob/main/internal/kokoro/vet.sh#L22-L23) the check? Does this just need to be copied inside the `v2` block?

**Comment by codyoss** [comment]
looks like it
