### ISSUE TITLE
Package should be in a subdirectory

### ISSUE THREAD

**Issue by broady** [googleapis/gax-go#23]
The package name should be the same as the final part of the path.

I suggest `github.com/googleapis/gax-go/gax`

**Comment by saicheems** [comment]
Ah didn't see this, please tag me in the future so I get notified

The hyphen in the name is unfortunate... Is adding a subpackage much better leaving it as is? Having another gax subpackage would make the import path redundant and the root of the repo would just have a single folder.

**Comment by jba** [comment]
We could also set up a redirect. gRPC does this. The code lives in github.com/grpc/grpc-go, but the import path is google.golang.org/grpc. Not sure if it's worth it here, because this package won't be seen much by users.

**Comment by broady** [comment]
Hmmm, yes. We decided not to expose options via this package at all, right? If so, no need.

But if we are exposing this package, then we should set up a redirect.

**Comment by jba** [comment]
Haven't decided yet, but we're moving towards that.

**Comment by saicheems** [comment]
We've moved to having client options in a different package - tentatively closing this, please reopen if you'd still like the redirect.
