### ISSUE TITLE
options should be a separate package

### ISSUE THREAD

**Issue by jba** [googleapis/gax-go#24]
For the handwritten clients, gax is an implementation detail, but it leaks through because it is the package that has the options.

Can we move options to their own package where they can be used by both handwritten and generated clients?

Suggested package names:

- options
- opts -- better, since it will be typed repeatedly: opts.WithThis(), opts.WithThat(), ...

Suggested import paths:

- github.com/googleapis/go/opts
- google.golang.org/api/opts

I'd be okay with pretty much anything that mentions APIs (not cloud, because they aren't cloud-specific).

@saicheems @mcgreevy @okdave @broady

**Comment by saicheems** [comment]
If we go for something like this, I don't think googleapis is the right org for it, so I'd say the second one you mentioned

Can this be a subpackage under gax? I realize gax is an implementation detail of toolkit, but it does stand for google api extensions after all

**Comment by okdave** [comment]
Can you explain why, for the handwritten clients, the cloud package is insufficient?

**Comment by jba** [comment]
These are Google API and/or gRPC options, so they are not specific to cloud. It would be a shame to duplicate them. It would also be a shame to have different packages for handwritten and generated clients.
