### ISSUE TITLE
Extensibility points for invoke

### ISSUE THREAD

**Issue by garye** [googleapis/gax-go#33]
I'm starting to look at using gax/invoke for retries in a cloud veneer client. There are some places where I think allowing callers to customize the behavior would be useful.

- I need to inspect an outgoing request to know if it is idempotent and therefore retryable. I don't want to pay the cost of this upfront, and would rather delay until after an error. Perhaps a `retryable` predicate as a `CallSetting` that gets used in addition to looking at the `RetryCodes` codes?

- There is no logging of an error before retrying so the underlying error gets lost if the deadline is eventually exceeded. Logging would be helpful, but it might be nice to have another `CallSetting` that lets me inspect the error to log, increment a failure counter, or otherwise allow some instrumentation of the code.

**Comment by pongad** [comment]
Closed by https://github.com/googleapis/toolkit/pull/434
