### ISSUE TITLE
SetPageSize should take an int

### ISSUE THREAD

**Issue by jba** [googleapis/gax-go#34]
The signature of an iterator's SetPageSize method should have an int arg, not int32. When setting the int32 page_size field of a request, the arg is silently truncated:

  req.PageSize = int32(pageSize)

**Comment by jba** [comment]
@okdave

**Comment by jba** [comment]
Correction: we want to truncate, not wrap:

if pageSize > math.MaxInt32 {
  pageSize = math.MaxInt32
}
req.PageSize = int32(pageSize)

**Comment by pongad** [comment]
This looks like a an issue in toolkit, not GAX. I'll open a PR there.
