### ISSUE TITLE
APIError.Error() nil pointer exception in some cases.

### ISSUE THREAD

**Issue by hime** [googleapis/gax-go#350]
I'm curious if getting a nil pointer exception when trying to get string version of APIError (using .Error()) documented. The issue arises when we attempt to run operations on the wrapped error field `APIError.err`. We are able to safely created using the `ParseError`.  However, when we call .Error() method on this error, we call `APIError.err.Error()` without checking if err field was set. 

#### Environment details
  - Package version: gax-go/v2 v2.12.3

#### Steps to reproduce

  1. Create API Error using [ParseError](https://github.com/googleapis/gax-go/blob/main/v2/apierror/apierror.go#L276)
  2. Call [(APIError).Error()](https://github.com/googleapis/gax-go/blob/main/v2/apierror/apierror.go#L203) on error.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by quartzmo** [comment]
Hi @hime,

Please provide a complete code example reproducing the issue you encountered, along with the expected output when running your example. Thanks!

**Comment by hime** [comment]
Hi @quartzmo, 

Here's a code example. Regarding the expected output, maybe we can leave the message unset if error is nil.

```
// You can edit this code!
// Click here and start typing
package main

import (
	"fmt"

	"github.com/googleapis/gax-go/v2/apierror"
	"google.golang.org/grpc/status"
)

func main() {
	err := status.New(500, "internal error").Err()
	apiErr, _ := apierror.ParseError(err, false)
	fmt.Println("Our error: ", apiErr.Error())
}
```

**Comment by quartzmo** [comment]
@hime Thanks for the quick reply. I reproduced the issue using your code example. I need to do some investigation into what the expected behavior is when the second `wrap` argument to `ParseError` is `false`. Thank you very much for reporting this bug.
