### ISSUE TITLE
gax-go: package needs package-level documentation

### ISSUE THREAD

**Issue by jacobsa** [googleapis/gax-go#38]
I stumbled upon the godoc for this package via a link from golang/oauth2#203, and immediately wondered "what the heck is gax"? There was no package-level documentation to answer this. Especially since it has such an odd name, it seems like this package needs some context.

**Comment by pongad** [comment]
@jacobsa Sorry I haven't gotten to this before. The code hasn't been changed in a while, so I lost track of the repo. Working on this now.
