### ISSUE TITLE
Panic in invoke.go

### ISSUE THREAD

**Issue by leadinglocally** [googleapis/gax-go#41]
Go 1.7

My server just died with this error. Thought I would let you know...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7507d2]

goroutine 584 [running]:
panic(0x939380, 0xc4200100e0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/googleapis/gax-go.Sleep(0x0, 0x0, 0x18071e29, 0xc6d6c902c4, 0xc6d6c902c0)
        /home/alex/go/src/github.com/googleapis/gax-go/invoke.go:56 +0x52
cloud.google.com/go/storage.runWithRetry(0x0, 0x0, 0xde8886fb08, 0xde8886faa8, 0xc5ea2f6de0)
        /home/alex/go/src/cloud.google.com/go/storage/invoke.go:39 +0xc2
cloud.google.com/go/storage.(*ObjectIterator).fetch(0xc602fc4150, 0x0, 0xd2e6d72dc0, 0xb0, 0x454799, 0xc44fe3c118, 0x7f0700000000, 0$
        /home/alex/go/src/cloud.google.com/go/storage/bucket.go:247 +0x543
cloud.google.com/go/storage.(*ObjectIterator).(cloud.google.com/go/storage.fetch)-fm(0x0, 0xd2e6d72dc0, 0xb0, 0x20, 0x974600, 0x1, 0$
        /home/alex/go/src/cloud.google.com/go/storage/bucket.go:194 +0x48
google.golang.org/api/iterator.(*PageInfo).fill(0xc7633c01e0, 0x0, 0xc44fe25c00, 0x4954d0)
        /home/alex/go/src/google.golang.org/api/iterator/iterator.go:143 +0x49
google.golang.org/api/iterator.(*PageInfo).next(0xc7633c01e0, 0x44ad5d, 0x8fa8c0)
        /home/alex/go/src/google.golang.org/api/iterator/iterator.go:122 +0x80
google.golang.org/api/iterator.(*PageInfo).(google.golang.org/api/iterator.next)-fm(0x974601, 0x5381a9)
        /home/alex/go/src/google.golang.org/api/iterator/iterator.go:100 +0x2a
cloud.google.com/go/storage.(*ObjectIterator).Next(0xc602fc4150, 0xc44fe3c0c0, 0xde8886fe68, 0xde8886fe88)
        /home/alex/go/src/cloud.google.com/go/storage/bucket.go:224 +0x2f
_/home/alex/_code/graphserver/poly.(*PolyGraph).Worker(0xc4200849c0)
        /home/alex/_code/graphserver/poly/workers.go:287 +0xb63
created by _/home/alex/_code/graphserver/poly.(*PolyGraph).StartWorkers
        /home/alex/_code/graphserver/poly/workers.go:128 +0xc98

**Comment by jba** [comment]
Thanks for the bug report. I'd like to see your call to BucketHandle.Objects. Is it possible that the context you're passing is nil? I get a similar stack trace when I do that.

**Comment by jba** [comment]
By the way, if that is the problem, then the correct solution is to pass a context -- either context.Background(), context.TODO() or something else. We can help you figure out what makes the most sense.

**Comment by jba** [comment]
Assuming no news is good news.

**Comment by leadinglocally** [comment]
This is not a solution, because the error only happens sometimes.

I'm pulling 3 million keys per minute from GS to my server.

**Comment by leadinglocally** [comment]
Why is there even a panic in these libs, and not a graceful handling of any errors?

**Comment by jba** [comment]
We don't check every value for being non-nil. 

Could you print the value of ctx before you call BucketHandle.Objects? And maybe share some of the code near that call, if it's not too sensitive?

**Comment by pongad** [comment]
Apologies for getting here so late. I believe @jba 's analysis is correct. This code path is for retrying request that has errored. It's likely that the error only happens sometimes, since most API calls (hopefully!) succeeds the first try.

**Comment by pongad** [comment]
Due to inactivity, I'll close this for now. Please reopen if required.
