### ISSUE TITLE
tag a new version

### ISSUE THREAD

**Issue by broady** [googleapis/gax-go#82]
v2.0.3 depends on grpc@v0.16, which has the bad lint dependency.

**Comment by dmitshur** [comment]
v1.0.1 is also affected, see [v1.0.1/go.mod](https://github.com/googleapis/gax-go/blob/v1.0.1/go.mod).

**Comment by jadekler** [comment]
I've tagged the latest commit as [1.0.2](https://github.com/googleapis/gax-go/releases/tag/v1.0.2) and [2.0.4](https://github.com/googleapis/gax-go/releases/tag/v2.0.4).

**Comment by dmitshur** [comment]
Thank you!

I'm not sure how important it is, but I noticed the `Version` constant is the previous value in both those tags.

**Comment by jadekler** [comment]
Shoot, I always forget that. It's not hyper critical - I'll try to remember next release.
