### ISSUE TITLE
Tag a new release sometime soon?

### ISSUE THREAD

**Issue by alyosha** [googleapis/gax-go#87]
## Summary
In the most recent release, the `v2` module still requires `go 1.12`, though this has since been removed by @jadekler in https://github.com/googleapis/gax-go/commit/b2b182669a42d221760db65e3d2622c3997c068e#diff-dc2e1be9e9810655cf485878bd63cde6

Go mod defaults to the latest release tag on the initial dependency pull, so anyone who is not on `1.12` or later will have to come here and debug a bit themselves

**Comment by jadekler** [comment]
Done:

- https://github.com/googleapis/gax-go/releases/tag/v2.0.5
- https://github.com/googleapis/gax-go/releases/tag/v1.0.3
