### ISSUE TITLE
go mod picking up wrong 2.0 version

### ISSUE THREAD

**Issue by jmhodges** [googleapis/gax-go#89]
When I run `go get github.com/googleapis/gax-go` using modules, the version I get is from the tag `v2.0.2+incompatible` (with sum  `h1:silFMLAnr330+NRuag/VjIGF7TLp/LBrV2CJKFLWEww=`), when it seems that `v2.0.5` is the latest.

Running a plain `go get -u` gets me `v1.0.3`.

What's happening? It feels like there's something that needs to happen from gax-go's end?

**Comment by noahdietz** [comment]
Hi @jmhodges! I was able to reproduce the behavior you've described. Please use the `v2` pkg path in your Go tool commands and/or `go.mod`.

`go get github.com/googleapis/gax-go/v2`

My `go.mod` changed like so:
`+       github.com/googleapis/gax-go/v2 v2.0.5`

I filed #90 to have the README updated.
